[package]
name = "sbits-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
sbits = { path = ".." }

[[bin]]
name = "bitvec_ops"
path = "fuzz_targets/bitvec_ops.rs"
test = false
doc = false
bench = false
